### ISSUE TITLE
NodeJS SDK Functions Missing API Responses and Types

### ISSUE THREAD

**Issue by kentond18** [ByteflowInc/nodejs-sdk#1]
In going to use the client, the SDK types do not match the API documentation for the responses corresponding to your docs. 

For example, your endpoint of [sendMessage](https://docs.byteflow.app/api-reference/endpoint/create) is expected to return 
```typescript
{
    sentWithRoute: string | undefined; 
    error: string | array | undefined;
}
```
– however, in the current SDK, it does not return such types to the client. Simply returns a void function for this type, leaving the user to be unable to successfully handle errors or return the sentWithRoute value to the user on a successful call.

None of the functions in the `index.ts` file contain defined return types on the functions, nor do they return the API responses to the client on completion of the API call.

**Comment by maxall41** [comment]
Sorry about this oversight. I have added return types to all public functions. You can use them in the latest version of the package: 1.3.5.

**Comment by kduprey** [comment]
This needs to be reopened. The types you added are returning the data that is embedded in the Axios response object, not the Axios Response Object with specified data return type, such as `axios.post<{sentWithRoute: string}>()`.

This in turn causes errors when going to access the fields on the response as it does not match what is being returned from the method.
